name: quiz_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  rflutter_alert: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  fonts:
    - family: DancingScript
      fonts:
        - asset: fonts/DancingScript-VariableFont_wght.ttf
    - family: AmaticSC
      fonts:
        - asset: fonts/AmaticSC-Bold.ttf
    - family: Dosis
      fonts:
        - asset: fonts/Dosis-VariableFont_wght.ttf
